---
- name: Install Docker (Ubuntu)
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install required packages
      apt:
        name:
          [
            "apt-transport-https",
            "ca-certificates",
            "curl",
            "software-properties-common",
          ]
        state: present
      become: true

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      become: true

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
        state: present
      become: true

    - name: Add user to Docker group
      become: yes
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true
      become: true