version: "3.8"

services:
  jenkins:
    build:
      context: ${repository_path}/jenkins/config
      dockerfile: dockerfile.jenkins
    container_name: jenkins
    restart: on-failure
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

  nginx:
    build:
      context: ${repository_path}/jenkins/config
      dockerfile: dockerfile.nginx
    container_name: nginx
    restart: always
    networks:
      - jenkins
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
  jenkins-docker-certs:
