---
- name: Deploy Jenkins
  hosts: jenkins_hosts
  vars_files:
    - encrypted_data

  #TODO: Convert this into a task to get the OS from the VM itself.
  vars_prompt:
    - name: VM_OS
      prompt: "Choose an option (ubuntu_aws_ec2)"
      private: no

  tasks:
    - name: Set VM_HOME variable based on selected VM_OS
      set_fact:
        VM_HOME: "{{ item.value }}"
      when: VM_OS == item.key
      loop:
        - { key: "ubuntu_aws_ec2", value: "/home/ubuntu" }

    - name: Add SSH Agent
      import_tasks: ../install-tasks/ssh_agent.yaml

    - name: Install Docker
      import_tasks: ../install-tasks/docker.yaml

    - name: Install Workspace
      import_tasks: ../install-tasks/workspace.yaml
