- name: Run socat container
  hosts: jenkins_hosts
  become: true

  tasks:
    - name: Run socat container
      community.general.docker_container:
        name: socat
        image: alpine/socat
        detach: yes
        restart_policy: always
        published_ports:
          - "127.0.0.1:2376:2375"
        networks:
          - name: config_jenkins
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"