- name: Run Docker container
  become: true

  docker_container:
    name: my_container
    image: alpine/socat
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    restart_policy: always
    ports:
      - "127.0.0.1:2376:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - name: jenkins