# Use the official Jenkins image as the base image
FROM jenkins/jenkins:latest

# Set up Jenkins home directory permissions
USER root
RUN chown -R jenkins:jenkins /var/jenkins_home

# Expose the Jenkins web interface port
EXPOSE 8080