# Use the official Jenkins image as the base image
FROM jenkins/jenkins:latest

# Copy Jenkins configuration files
COPY config.xml /var/jenkins_home/config.xml
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

# Install plugins from plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# Set up Jenkins home directory permissions
USER root
RUN chown -R jenkins:jenkins /var/jenkins_home

# Expose the Jenkins web interface port
EXPOSE 8080

# Start Jenkins
CMD ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]
