- name: Copy github SSH keys
  copy:
    content: "{{ item.value }}"
    dest: "{{ VM_HOME }}/.ssh/{{ item.key }}"
    owner: ubuntu
    group: ubuntu
    mode: 0600
  become: true
  loop:
    - { key: "github", value: "{{ github }}" }
    - { key: "github.pub", value: "{{ github_pub }}" }

- name: Copy config file
  copy:
    content: "{{ item.value | string }}"
    dest: "{{ VM_HOME }}/.ssh/{{ item.key }}"
    owner: ubuntu
    group: ubuntu
  become: true
  loop:
    - { key: "config", value: "{{ config }}" }

- name: Starting an SSH Agent
  shell: |
    #!/bin/bash

    eval $(ssh-agent)
    ssh-add {{ VM_HOME }}/.ssh/github
  become: true
