- name: Create a workspace directory
  file:
    path: "{{ VM_HOME }}/workspace"
    state: directory

- name: Clone all the repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ VM_HOME }}/workspace/{{ item.name }}"
    clone: yes
  loop: "{{ repos }}"
  vars:
    repos:
      - name: devops-toolkit
        repo: https://github.com/AakshRanjan/devops-toolkit.git
      - name: advanced-logging
        repo: https://github.com/AakshRanjan/advanced_logging.git
